### ISSUE TITLE
分享一个上生产的云原生“玩具”

### ISSUE THREAD

**Issue by spencercjh** [Zheaoli/weekly-share#14]
大家好呀，我是spencer，可以叫我阿蔡。

作为群里少数的在校学生，做分享和实验室开组会一样压力山大，深怕耽误受众的宝贵的时间。有说的不对的地方，还请大家多多指正。我只会写 Java ，Java-style Python ，一点 Kotlin ，一点点 Go 和 Cpp 。CRUD 的那些事情不好意思多说了，第一次分享，来聊点时髦且轻松的内容……

**推荐使用 PC 查看本文。**

# Argo

![image](https://user-images.githubusercontent.com/29922079/109966010-b2651700-7d2a-11eb-92e7-e894564811f9.png)

[Argo](https://argoproj.github.io/) 是 [CNCF](https://cncf.io/) 旗下的一个项目，其中包括4个子项目：

* [Workflows](https://argoproj.github.io/projects/argo)
* [Continuous Delivery](https://argoproj.github.io/projects/argo-cd)
* [Events](https://argoproj.github.io/projects/argo-events)
* [rollouts](https://argoproj.github.io/argo-rollouts/)

在[前司](https://inceptio.ai)实习的 10 个月的时间里，大概有 1/3 的时间都在使用 Argo Workflows 。其他子项目没用过，不了解，我就不复制粘贴文档了。

所以今天给大家介绍一下这个“云原生”“玩具”是怎么玩的。我暂时没有能力给大家讲它底层和 K8s 的关系和细节，想看这部分内容的朋友抱歉了。

### Overview

https://www.youtube.com/watch?v=TZgLkCFQ2tk

一句话概括：**一个在 K8s 上的容器原生的并行任务工作流编排引擎（调用 K8s 的 APIs）。**

[Repo](https://github.com/argoproj/argo-workflows/#features) 里的介绍更详细。

划下重点：
* 并行工作任务的编排；
* Workflows 是对K8s CRD（ [Custom Resource Definition](https://kubernetes.io/zh/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/) ）的实现；
* 每一步（steps）都是容器；
* 可以用顺序的任务或 DAG 来建立工作流，支持循环、分支条件；
* 计算密集型应用；
* 还能跑 CI/CD；
* 没有额外的 vm，server 环境限制；
* 所有的 K8s 都能跑（比如本地）；
* 有UI可以耍（不好用）；
* K8s资源控制，支持阿里云 OSS（新feature，没用过）；
* …………

### 如何安装

![image](https://user-images.githubusercontent.com/29922079/109966163-e3dde280-7d2a-11eb-8dd4-c7e681f411b5.png)

更难的是怎么装 K8s……Argo Workflows 本身是很容易[安装](https://argoproj.github.io/argo-workflows/quick-start/#install-argo-workflows) 的。可以说，如果集群是就绪的，Argo Workflows 是开箱即用的。

### 如何面向 Yaml 编程

![image](https://user-images.githubusercontent.com/29922079/109968517-c6f6de80-7d2d-11eb-9a00-54188ca2b6bf.png)

![image](https://user-images.githubusercontent.com/29922079/109968931-44225380-7d2e-11eb-9e44-f032bb395fce.png)

非常像 Github Action，大家应该都玩过那个的。

Yaml 山警告！（狗头

#### official Hello World

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
  - name: whalesay              # name of the template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
      resources:                # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
```

![image](https://user-images.githubusercontent.com/29922079/109969011-5b614100-7d2e-11eb-9233-5365da6ac6b8.png)

#### 控制流

when

```yaml
# 上一步 “READY” 后才会执行这步，不能让上一步非 0 退出来实现。这会导致整个 workflow 误报为失败
- - name: fetch-annotation-results-step
  template: fetch-annotation-results
  when: "'{{steps.fetch-submitted-annotation-sub-tasks-step.outputs.result}}' == 'READY'"
  arguments:
    parameters:
      # format: [{"resource_id":"","batch_id":""}]
      - name: annotation_task_id
        value: "{{inputs.parameters.annotation_task_id}}"
```

for-each

```yaml
# 上一步的 outputs 作为这一步需要遍历的参数列表
- - name: sync-annotation-task-results-step
      template: sync-annotation-task-results
      arguments:
        parameters:
          - name: annotation_task_id
            value: "{{item}}"
      withParam: "{{steps.fetch-submitted-annotation-tasks-step.outputs.result}}"
```

#### Yaml里贴又臭又长的源码，恶心同事（狗头

**在我建立了 Argo Workflows container 代码模板后（一个Python code template repo），大家就不怎么在 Yaml 里贴屎山了。**

```yaml
# 只展示一些templates

# 写 Py
- name: fetch-submitted-annotation-tasks
        script:
          image: registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/infra_python:3.7-slim-all
          command: [python]
          source: |
            print("Hello World!")
# 写 curl
- name: cry
      container:
        image: curlimages/curl:7.67.0
        command: ["curl", "-H", "Content-Type: application/json", "-d", '{"msgtype":"markdown", "markdown": {"content": "**<font color=\"warning\">[FAILED]</font>**\n 数据打包失败: $(ANNOTATION_TASK_ID)\n Check workflow: `argo get -n argo-hubble $(WORKFLOW_NAME)`"}}', "$(WEBHOOK_URL)"]
      env:
                # workflow.name 全局metadata
                - name: WORKFLOW_NAME
                  value: "{{workflow.name}}"
                # workflow.parameters 全局参数，一开始传进来的参数
                - name: ANNOTATION_TASK_ID
                  value: "{{workflow.parameters.annotation_task_id}}"
                # 集群那边配的 secret
                - name: WEBHOOK_URL
                  valueFrom:
                    configMapKeyRef:
                      name: cluster-configs
                      key: annotation_failed_webhook
```

#### 无缝衔接阿里云

```yaml
spec:
    volumes:
    # 集群那边配的 secret
    - name: cas-service-token
      secret:
        secretName: cas-service-token
    volumeClaimTemplates:
    - metadata:
        name: argo-hubble-data-claim
      spec:
        # 挂载 NAS
        storageClassName: "alicloud-flexvolume-extreme-nas-sc"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 60Gi
```

#### 资源控制

```yaml
# 某个 container
resources:
  limits:
    nvidia.com/gpu: "1"

# 重试策略
- name: regenerate-p1
  retryStrategy:
    limit: 5
    retryPolicy: "Always"
    backoff:
      duration: "1m"
      factor: 1
      maxDuration: "30m"
```

### 我的情况

作为一个实习小兵，我就像万精油一样，和老板一起干几个项目。有一天 leader 问我，你会写 Python 吗，我说我只会写 Java 味 Python。他说没事，上吧。然后我就被叫去写这个东西上面的 Python 业务。因为我和用户（算法工程师、测试经理）接触的不多，对业务的熟悉程度和正式工不能比，故只能写一些几句话，一张图就能说清楚的业务。比如，拉一下这些数据，把他们上传到哪里哪里，拉一下那些数据，给企业微信发几条消息，等等。从一个 image 写起，久而久之，到写一个完整的，业务有点复杂的 Workflow 。

### 为什么用它

类似于 Apache Airflow，机器学习领域的 Kubeflow （我都没用过），编排任务。比如：数据预处理、机器学习等等。但为什么用这个，不用别的呢？我就不知道了，懂的说说。

#### 开发 Workflows

![image](https://user-images.githubusercontent.com/29922079/109970426-00304e00-7d30-11eb-99fe-0e666db8b453.png)

有些 Workflows 里的逻辑是领域专家提供的，我们擦一下屁股以后完成容器化，有些是我们自己写的。编排一下，粘贴进来一些 notification/cry 的 steps ，就是一个 Workflow 了。但往往没那么简单，我们会在纸头上画一画任务树草稿，推演整个 Workflow 的执行过程。

![image](https://user-images.githubusercontent.com/29922079/109970218-c0696680-7d2f-11eb-82d9-72849479aaa1.png)

#### 使用 Workflows

![image](https://user-images.githubusercontent.com/29922079/109967154-07edf380-7d2c-11eb-8c32-cd0a57e44a90.png)

一个同事用 Go 写了一个 Argo Workflows 的 gRPC 服务（我也参与过，哈哈），它极大地降低了接入 Workflow 的成本——只需要知道：发一个 POST 请求（或者gRPC请求） ，body 里携带好参数，就能运行一个预先创建好的 Workflow 。所有服务都能去调这个服务； 。

![image](https://user-images.githubusercontent.com/29922079/109969751-3a4d2000-7d2f-11eb-9600-ff76b4463536.png)

主要有以下2个使用场景：

* 自动：数据进了数据库后异步触发；
* 手动：相关人员在网页上手动触发 Workflow ，查看 Workflow 详情。

![image](https://user-images.githubusercontent.com/29922079/109967972-0f61cc80-7d2d-11eb-9743-119f8f4d35c4.png)
![image](https://user-images.githubusercontent.com/29922079/109968262-7089a000-7d2d-11eb-8420-3de666dace84.png)
![image](https://user-images.githubusercontent.com/29922079/109968727-0c1b1080-7d2e-11eb-83d0-8a8a3a8b79a3.png)

### 团队实践中遇到的问题

_你们可能已经想到了N个使用问题，看看有没有被你猜中的。_

* 不适合多而小的任务（增加了 K8s 管理人员的工作）
 
![image](https://user-images.githubusercontent.com/29922079/109967848-e3dee200-7d2c-11eb-8579-7b11cebdba3e.png)

 
Pod 数量爆炸，超过集群负载能力，DevOps 和 SRE 想砍我（们）。倒逼我们把一些循环逻辑放进 container 内部，并尽可能地减少无效的容器启动（跑了个if后就跳出了）。大量的Pod好像还带来了更严重，奇怪的问题，过去快半年了，忘记细节了。

* 任务可观测性不强

stdout 会被当成 output。要想有日志，就要把预期结果输出到文件，会多出一些 python 和 yaml 代码。日志的效果如前文 Hello World Demo 所示。如果不打清楚日志，有时候某个 step 转瞬而过，或者 Workflow在 Argo Workflows UI 上看不到了（如果有 Workflow Id 的话还能用 API GET 到），就不知道发生了什么。Argo Workflows 这边没有接入任何的日志服务，所以一开始有些混乱。后来我们组里强调：容易出问题的地方要有日志，要多用企业微信 bot 做通知，用企业微信聊天记录做持久性存储，用户想查就能查到。后来，组里相关的前端跟进后，结合 Grafana ，这个问题就慢慢解决了。

![image](https://user-images.githubusercontent.com/29922079/109968560-d4ac6400-7d2d-11eb-9761-1a3f2804b6e9.png)
![image](https://user-images.githubusercontent.com/29922079/109968473-b5add200-7d2d-11eb-982d-c7c376c7b56c.png)

* Argo Workflows 自带的 UI 过于难用

就像阿里云的 SLS 一样，这个 [Argo Workflows UI](https://github.com/argoproj/argo-workflows/tree/master/ui) 的性能真的很糟糕，同屏 steps 非常多的时候会很卡，交互也不好。而且它并不是一个完整的“ Workflow 管理系统”。根据官方文档，它只能查看活着的 Workflows 。 结合上文，当你想去网上看看到底发生了什么的时候，运气不好你可能会一无所获。每当我吐槽这些的时候，老板就安慰我说人家的重点不在这，lol。后来，组里相关的前端一发力，大部分情况下都不用它了。用户和我们开发者都用同一套前端看 Workflow 详情了。

* 需要对 K8s 有一定的了解

后面新来的实习生，容器都不是特别懂，就很难上手。（也可能是个例吧，不知道现在咋样了）

* 调试

写业务的时候，单独调 image 的业务代码就行了。更进一步，联调 Workflow 的时候需要本地 K8s 的支持。

# 最后

你们有没有面向Yaml编程的经历，来聊聊你司的“云原生”经历吧！
